# Generated by Django 4.2.3 on 2023-07-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_album_cover_artist_image_band_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='artists',
            new_name='artist',
        ),
    ]
